version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      
